<a href="https://colab.research.google.com/github/Ayush04H/Car-Rental-Project/blob/main/CarRentalU2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import *

# **Import Dataset**

In [2]:
dataset=pd.read_csv('CarRentalData.csv')
dataset.head()

fuelType  rating  renterTripsTaken  reviewCount               city country  \
0  GASOLINE     5.0                 1            1              Miami      US   
1  GASOLINE     NaN                 0            0           Monument      US   
2  GASOLINE     NaN                 0            0  Sunny Isles Beach      US   
3  GASOLINE     5.0                 3            2  Sunny Isles Beach      US   
4       NaN     4.8                21           15        Miami Beach      US   

    latitude   longitude state        id  rate         makers       model  \
0  25.762867  -80.189340    FL    864946  1500    Rolls Royce       Ghost   
1  39.065143 -104.833966    CO  15248243  1485           Ford     Mustang   
2  25.952209  -80.120557    FL    864946  1400  Mercedes-Benz     G-Class   
3  25.952512  -80.119771    FL    864946  1200   Aston Martin  V8 Vantage   
4  25.791807  -80.128564    FL   9541863  1199    Lamborghini     Huracan   

   year   type  
0  2011  sedan  
1  2020  sedan  
2  2015    suv  
3  2013  sedan  
4  2019  sedan

from matplotlib import pyplot as plt
_df_0['rating'].plot(kind='hist', bins=20, title='rating')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['renterTripsTaken'].plot(kind='hist', bins=20, title='renterTripsTaken')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['reviewCount'].plot(kind='hist', bins=20, title='reviewCount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['latitude'].plot(kind='hist', bins=20, title='latitude')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('city').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('state').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('makers').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_7.groupby('model').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='rating', y='renterTripsTaken', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9.plot(kind='scatter', x='renterTripsTaken', y='reviewCount', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_10.plot(kind='scatter', x='reviewCount', y='latitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_11.plot(kind='scatter', x='latitude', y='longitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('city')):
  _plot_series(series, series_name, i)
  fig.legend(title='city', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('state')):
  _plot_series(series, series_name, i)
  fig.legend(title='state', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_14.sort_values('year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('makers')):
  _plot_series(series, series_name, i)
  fig.legend(title='makers', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_15.sort_values('year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('model')):
  _plot_series(series, series_name, i)
  fig.legend(title='model', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
_df_16['rating'].plot(kind='line', figsize=(8, 4), title='rating')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17['renterTripsTaken'].plot(kind='line', figsize=(8, 4), title='renterTripsTaken')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_18['reviewCount'].plot(kind='line', figsize=(8, 4), title='reviewCount')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_19['latitude'].plot(kind='line', figsize=(8, 4), title='latitude')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['state'].value_counts()
    for x_label, grp in _df_20.groupby('city')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('city')
_ = plt.ylabel('state')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['makers'].value_counts()
    for x_label, grp in _df_21.groupby('state')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('state')
_ = plt.ylabel('makers')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['model'].value_counts()
    for x_label, grp in _df_22.groupby('makers')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('makers')
_ = plt.ylabel('model')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['type'].value_counts()
    for x_label, grp in _df_23.groupby('model')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('model')
_ = plt.ylabel('type')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_24['city'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_24, x='rating', y='city', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_25['state'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_25, x='rating', y='state', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_26['makers'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_26, x='rating', y='makers', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_27['model'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_27, x='rating', y='model', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

**To Check for the null values**

In [3]:
dataset.isnull().sum()

fuelType             91
rating              585
renterTripsTaken      0
reviewCount           0
city                  0
country               0
latitude              0
longitude             0
state                 0
id                    0
rate                  0
makers                0
model                 0
year                  0
type                  0
dtype: int64

# **No Of Rows And Columns**

In [4]:
dataset.shape

(6646, 15)

# **Description of Data**

In [5]:
dataset.describe()

rating  renterTripsTaken  reviewCount     latitude    longitude  \
count  6061.000000       6646.000000  6646.000000  6646.000000  6646.000000   
mean      4.919244         32.719982    27.758050    35.545377   -99.259664   
std       0.178962         41.020738    34.354543     6.405019    20.306032   
min       1.000000          0.000000     0.000000    21.272565  -158.165693   
25%       4.900000          5.000000     4.000000    32.021705  -117.048933   
50%       5.000000         18.000000    15.000000    35.186542   -95.439594   
75%       5.000000         45.000000    39.000000    39.954439   -81.756580   
max       5.000000        395.000000   321.000000    64.893610   -68.823637   

                 id         rate         year  
count  6.646000e+03  6646.000000  6646.000000  
mean   5.827824e+06    93.097502  2015.324857  
std    4.695539e+06    92.513099     4.039303  
min    5.105000e+03    20.000000  1955.000000  
25%    1.575230e+06    45.000000  2013.000000  
50%    4.670126e+06    69.000000  2016.000000  
75%    9.459412e+06   110.000000  2018.000000  
max    1.581088e+07  1500.000000  2020.000000

from matplotlib import pyplot as plt
_df_28['rating'].plot(kind='hist', bins=20, title='rating')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_29['renterTripsTaken'].plot(kind='hist', bins=20, title='renterTripsTaken')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_30['reviewCount'].plot(kind='hist', bins=20, title='reviewCount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_31['latitude'].plot(kind='hist', bins=20, title='latitude')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_32.plot(kind='scatter', x='rating', y='renterTripsTaken', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_33.plot(kind='scatter', x='renterTripsTaken', y='reviewCount', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_34.plot(kind='scatter', x='reviewCount', y='latitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_35.plot(kind='scatter', x='latitude', y='longitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_36.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['renterTripsTaken']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_37.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('renterTripsTaken')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['reviewCount']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_38.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('reviewCount')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['year']
  ys = series['latitude']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_39.sort_values('year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('year')
_ = plt.ylabel('latitude')

from matplotlib import pyplot as plt
_df_40['rating'].plot(kind='line', figsize=(8, 4), title='rating')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_41['renterTripsTaken'].plot(kind='line', figsize=(8, 4), title='renterTripsTaken')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_42['reviewCount'].plot(kind='line', figsize=(8, 4), title='reviewCount')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_43['latitude'].plot(kind='line', figsize=(8, 4), title='latitude')
plt.gca().spines[['top', 'right']].set_visible(False)

**Dealing with the Null data**

In [6]:
dataset['fuelType'].fillna(method ='ffill',  inplace = True)
dataset['rating'].fillna(method ='ffill',  inplace = True)
dataset.isnull().sum()

fuelType            0
rating              0
renterTripsTaken    0
reviewCount         0
city                0
country             0
latitude            0
longitude           0
state               0
id                  0
rate                0
makers              0
model               0
year                0
type                0
dtype: int64

# Encoding IndeDependent Variable

# **Encoding The Dependent Variable**

In [7]:
dataset['type'].value_counts()

sedan      3664
suv        1780
truck       573
minivan     464
van         165
Name: type, dtype: int64

In [8]:
dataset.replace({'type':{'sedan':0,'suv':1,'minivan':2,'truck':3,'van':4},'country':{'US':1}},inplace=True)
dataset.head()

fuelType  rating  renterTripsTaken  reviewCount               city  \
0  GASOLINE     5.0                 1            1              Miami   
1  GASOLINE     5.0                 0            0           Monument   
2  GASOLINE     5.0                 0            0  Sunny Isles Beach   
3  GASOLINE     5.0                 3            2  Sunny Isles Beach   
4  GASOLINE     4.8                21           15        Miami Beach   

   country   latitude   longitude state        id  rate         makers  \
0        1  25.762867  -80.189340    FL    864946  1500    Rolls Royce   
1        1  39.065143 -104.833966    CO  15248243  1485           Ford   
2        1  25.952209  -80.120557    FL    864946  1400  Mercedes-Benz   
3        1  25.952512  -80.119771    FL    864946  1200   Aston Martin   
4        1  25.791807  -80.128564    FL   9541863  1199    Lamborghini   

        model  year  type  
0       Ghost  2011     0  
1     Mustang  2020     0  
2     G-Class  2015     1  
3  V8 Vantage  2013     0  
4     Huracan  2019     0

from matplotlib import pyplot as plt
_df_44['rating'].plot(kind='hist', bins=20, title='rating')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_45['renterTripsTaken'].plot(kind='hist', bins=20, title='renterTripsTaken')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_46['reviewCount'].plot(kind='hist', bins=20, title='reviewCount')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_47['latitude'].plot(kind='hist', bins=20, title='latitude')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_48.groupby('city').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_49.groupby('state').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_50.groupby('makers').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_51.groupby('model').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_52.plot(kind='scatter', x='rating', y='renterTripsTaken', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_53.plot(kind='scatter', x='renterTripsTaken', y='reviewCount', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_54.plot(kind='scatter', x='reviewCount', y='latitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_55.plot(kind='scatter', x='latitude', y='longitude', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['country']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_56.sort_values('country', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('city')):
  _plot_series(series, series_name, i)
  fig.legend(title='city', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('country')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['country']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_57.sort_values('country', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('state')):
  _plot_series(series, series_name, i)
  fig.legend(title='state', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('country')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['country']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_58.sort_values('country', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('makers')):
  _plot_series(series, series_name, i)
  fig.legend(title='makers', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('country')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['country']
  ys = series['rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_59.sort_values('country', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('model')):
  _plot_series(series, series_name, i)
  fig.legend(title='model', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('country')
_ = plt.ylabel('rating')

from matplotlib import pyplot as plt
_df_60['rating'].plot(kind='line', figsize=(8, 4), title='rating')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_61['renterTripsTaken'].plot(kind='line', figsize=(8, 4), title='renterTripsTaken')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_62['reviewCount'].plot(kind='line', figsize=(8, 4), title='reviewCount')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_63['latitude'].plot(kind='line', figsize=(8, 4), title='latitude')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['state'].value_counts()
    for x_label, grp in _df_64.groupby('city')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('city')
_ = plt.ylabel('state')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['makers'].value_counts()
    for x_label, grp in _df_65.groupby('state')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('state')
_ = plt.ylabel('makers')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['model'].value_counts()
    for x_label, grp in _df_66.groupby('makers')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('makers')
_ = plt.ylabel('model')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_67['city'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_67, x='rating', y='city', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_68['state'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_68, x='rating', y='state', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_69['makers'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_69, x='rating', y='makers', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_70['model'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_70, x='rating', y='model', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [9]:
dataset['type'].value_counts()

0    3664
1    1780
3     573
2     464
4     165
Name: type, dtype: int64

In [10]:
x=dataset.drop(['type','latitude','longitude','id'],axis=1)
y=dataset['type']

In [11]:
pd.DataFrame(x)

fuelType  rating  renterTripsTaken  reviewCount               city  \
0     GASOLINE    5.00                 1            1              Miami   
1     GASOLINE    5.00                 0            0           Monument   
2     GASOLINE    5.00                 0            0  Sunny Isles Beach   
3     GASOLINE    5.00                 3            2  Sunny Isles Beach   
4     GASOLINE    4.80                21           15        Miami Beach   
...        ...     ...               ...          ...                ...   
6641  GASOLINE    4.89                26           19      Sandy Springs   
6642  GASOLINE    4.79                45           38            Atlanta   
6643  GASOLINE    5.00                10            9            Atlanta   
6644  GASOLINE    4.97                41           35            Atlanta   
6645  GASOLINE    4.69                14           13      Sandy Springs   

      country state  rate         makers               model  year  
0           1    FL  1500    Rolls Royce               Ghost  2011  
1           1    CO  1485           Ford             Mustang  2020  
2           1    FL  1400  Mercedes-Benz             G-Class  2015  
3           1    FL  1200   Aston Martin          V8 Vantage  2013  
4           1    FL  1199    Lamborghini             Huracan  2019  
...       ...   ...   ...            ...                 ...   ...  
6641        1    GA   199     Land Rover   Range Rover Velar  2018  
6642        1    GA    57            BMW                  X5  2009  
6643        1    GA    57           Jeep             Compass  2018  
6644        1    GA   112           Jeep  Wrangler Unlimited  2019  
6645        1    GA   269       Maserati             Levante  2020  

[6646 rows x 11 columns]

In [12]:
pd.DataFrame(y)

type
0        0
1        0
2        1
3        0
4        0
...    ...
6641     1
6642     1
6643     1
6644     1
6645     1

[6646 rows x 1 columns]

In [13]:
x = pd.DataFrame(x)
for column in x.columns:
  print(column)

fuelType
rating
renterTripsTaken
reviewCount
city
country
state
rate
makers
model
year


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(dtype=np.int32,sparse=False),[0,4,6,8,9])],remainder='passthrough')
x=ct.fit_transform(x)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [15]:
pd.DataFrame(x)

0     1     2     3     4     5     6     7     8     9     ...  1597  \
0      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
6641   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6642   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6643   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6644   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
6645   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      1598  1599  1600  1601  1602  1603  1604    1605    1606  
0      0.0   0.0   0.0  5.00   1.0   1.0   1.0  1500.0  2011.0  
1      0.0   0.0   0.0  5.00   0.0   0.0   1.0  1485.0  2020.0  
2      0.0   0.0   0.0  5.00   0.0   0.0   1.0  1400.0  2015.0  
3      0.0   0.0   0.0  5.00   3.0   2.0   1.0  1200.0  2013.0  
4      0.0   0.0   0.0  4.80  21.0  15.0   1.0  1199.0  2019.0  
...    ...   ...   ...   ...   ...   ...   ...     ...     ...  
6641   0.0   0.0   0.0  4.89  26.0  19.0   1.0   199.0  2018.0  
6642   0.0   0.0   0.0  4.79  45.0  38.0   1.0    57.0  2009.0  
6643   0.0   0.0   0.0  5.00  10.0   9.0   1.0    57.0  2018.0  
6644   0.0   0.0   0.0  4.97  41.0  35.0   1.0   112.0  2019.0  
6645   0.0   0.0   0.0  4.69  14.0  13.0   1.0   269.0  2020.0  

[6646 rows x 1607 columns]

# **Split Test and Train data**

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [17]:
pd.DataFrame(X_train)

0     1     2     3     4     5     6     7     8     9     ...  1597  \
0      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5311   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5312   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  ...   0.0   
5313   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5314   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5315   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      1598  1599  1600  1601  1602  1603  1604   1605    1606  
0      0.0   0.0   0.0  4.85   0.0   0.0   1.0  175.0  2015.0  
1      0.0   0.0   0.0  4.84  30.0  25.0   1.0   86.0  2014.0  
2      0.0   0.0   0.0  5.00   3.0   3.0   1.0  100.0  2016.0  
3      0.0   0.0   0.0  5.00  45.0  42.0   1.0  129.0  2013.0  
4      0.0   0.0   0.0  5.00   6.0   3.0   1.0   20.0  2008.0  
...    ...   ...   ...   ...   ...   ...   ...    ...     ...  
5311   0.0   0.0   0.0  5.00  12.0   9.0   1.0  149.0  2019.0  
5312   0.0   0.0   0.0  4.95  51.0  42.0   1.0   37.0  2010.0  
5313   0.0   0.0   0.0  4.89  72.0  64.0   1.0   52.0  2015.0  
5314   0.0   0.0   0.0  5.00   0.0   0.0   1.0  250.0  2009.0  
5315   0.0   0.0   0.0  4.67  62.0  51.0   1.0   38.0  2008.0  

[5316 rows x 1607 columns]

In [18]:
pd.DataFrame(X_test)

0     1     2     3     4     5     6     7     8     9     ...  1597  \
0      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1325   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1326   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1327   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1328   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1329   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      1598  1599  1600  1601   1602  1603  1604   1605    1606  
0      0.0   0.0   0.0  4.69  119.0  89.0   1.0   69.0  2012.0  
1      0.0   0.0   0.0  5.00   18.0  14.0   1.0   38.0  2017.0  
2      0.0   0.0   0.0  4.98   53.0  44.0   1.0  230.0  2016.0  
3      0.0   0.0   0.0  4.94   17.0  17.0   1.0   85.0  2015.0  
4      0.0   0.0   0.0  5.00   48.0  44.0   1.0  115.0  2018.0  
...    ...   ...   ...   ...    ...   ...   ...    ...     ...  
1325   0.0   0.0   0.0  5.00    3.0   2.0   1.0   30.0  2018.0  
1326   0.0   0.0   0.0  5.00    7.0   6.0   1.0   77.0  2017.0  
1327   0.0   0.0   0.0  4.74  102.0  87.0   1.0   30.0  2014.0  
1328   0.0   0.0   0.0  5.00   19.0  16.0   1.0   72.0  2017.0  
1329   0.0   0.0   0.0  5.00    0.0   0.0   1.0  350.0  2019.0  

[1330 rows x 1607 columns]

# **Feature scaling**

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
np.asarray(X_test[0])

array([-0.12516706, -0.33032933,  0.43992488, ...,  0.        ,
       -0.26075392, -0.81159258])

# **Training The SVC Model**

In [21]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

# **Predicting of The Test Set**

In [22]:
y_pred=classifier.predict(X_test)

# **Confusion Metrics and accuracy score**

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test, y_pred)
print('The Accuracy for the Model will be :',acc*100,'%')

[[699   6   0  17   2]
 [ 16 346   0   6   3]
 [  0   0  98   0   0]
 [ 16  10   1  74   0]
 [  5   6   1   0  24]]
The Accuracy for the Model will be : 93.30827067669173 %


# **Making A Predictive System**

In [24]:
n=int(input("Enter the Number of Data Upto which u want to check the data in X_test"))
for a in range(0,n+1):
  inp=X_test[a].reshape(1,-1)
  prediction=classifier.predict(inp)
  print(prediction)
  if(prediction==0):
    print("The Vehicle Rented is a Car as it is mapped with value ",prediction)
  elif(prediction==1):
    print("The Vehicle Rented is a SUV as it is mapped with value ",prediction)
  elif(prediction==2):
    print("The Vehicle Rented is a minivan as it is mapped with value ",prediction)
  elif(prediction==3):
    print("The Vehicle Rented is a truck as it is mapped with value ",prediction)
  elif(prediction==4):
    print("The Vehicle Rented is a van as it is mapped with value ",prediction)
  else:
    print('Unable to Predict')

Enter the Number of Data Upto which u want to check the data in X_test50
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[3]
The Vehicle Rented is a truck as it is mapped with value  [3]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a S

# **Training the Decission Tree Model**

In [25]:
from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier1.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# **Predicting of test**

In [26]:
y_pred1=classifier1.predict(X_test)

# **Confusion metrics and Accuracy**

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred1)
print(cm)
acc=accuracy_score(y_test, y_pred1)
print('The Accuracy for the Model will be :',acc*100,'%')

[[684  24   0  13   3]
 [ 37 332   0   2   0]
 [  0   0  98   0   0]
 [ 21   9   1  70   0]
 [  5   6   1   0  24]]
The Accuracy for the Model will be : 90.82706766917293 %


# **Making a Preditive System**

In [28]:
n=int(input("Enter the Number of Data Upto which u want to check the data in X_test"))
for a in range(0,n+1):
  inp1=X_test[a].reshape(1,-1)
  prediction1=classifier1.predict(inp1)
  print(prediction1)
  if(prediction1==0):
    print("The Vehicle Rented is a Car as it is mapped with value ",prediction1)
  elif(prediction1==1):
    print("The Vehicle Rented is a SUV as it is mapped with value ",prediction1)
  elif(prediction1==2):
    print("The Vehicle Rented is a minivan as it is mapped with value ",prediction1)
  elif(prediction1==3):
    print("The Vehicle Rented is a truck as it is mapped with value ",prediction1)
  elif(prediction1==4):
    print("The Vehicle Rented is a van as it is mapped with value ",prediction1)
  else:
    print('Unable to Predict')

Enter the Number of Data Upto which u want to check the data in X_test50
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[3]
The Vehicle Rented is a truck as it is mapped with value  [3]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a S

# **Training the Random Forest Model**

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, max_features=14)
classifier2.fit(X_train, y_train)

RandomForestClassifier(max_features=14)

# **Predicting of test**

In [30]:
y_pred2=classifier2.predict(X_test)

# **Confusion metrics and Accuracy**

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred2)
print(cm)
acc=accuracy_score(y_test, y_pred2)
print('The Accuracy for the Model will be :',acc*100,'%')

[[699   7   0  15   3]
 [ 45 320   0   6   0]
 [  2   0  96   0   0]
 [ 22   8   1  70   0]
 [  5   6   1   0  24]]
The Accuracy for the Model will be : 90.90225563909775 %


# **Making a Preditive System**

In [32]:
n=int(input("Enter the Number of Data Upto which u want to check the data in X_test"))
for a in range(0,n+1):
  inp2=X_test[a].reshape(1,-1)
  prediction2=classifier2.predict(inp2)
  print(prediction2)
  if(prediction2==0):
    print("The Vehicle Rented is a Car as it is mapped with value ",prediction2)
  elif(prediction2==1):
    print("The Vehicle Rented is a SUV as it is mapped with value ",prediction2)
  elif(prediction2==2):
    print("The Vehicle Rented is a minivan as it is mapped with value ",prediction2)
  elif(prediction2==3):
    print("The Vehicle Rented is a truck as it is mapped with value ",prediction2)
  elif(prediction2==4):
    print("The Vehicle Rented is a van as it is mapped with value ",prediction2)
  else:
    print('Unable to Predict')

Enter the Number of Data Upto which u want to check the data in X_test50
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[3]
The Vehicle Rented is a truck as it is mapped with value  [3]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a SUV as it is mapped with value  [1]
[0]
The Vehicle Rented is a Car as it is mapped with value  [0]
[1]
The Vehicle Rented is a S